require('plugins')
require('options')
require('keybindings')
require('treesitter-config')
require('nvimtree-config')
require('telescope-config')
require('autopairs-config')
--require('vsnip-config')
require('escape-config')
require('comment-config')
require('onedark-config')
require('lsp-config')
require('whichkey-config')

